//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CefClient.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CefClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {&quot;id&quot;:&quot;f9add9d82c404a4f926698cc628194e9&quot;,&quot;bid&quot;:[{&quot;adzoneId&quot;:&quot;1822398137946503&quot;,&quot;admnative&quot;:{&quot;title&quot;:&quot;都2026了，赶紧来看&quot;,&quot;imgs&quot;:[{&quot;url&quot;:&quot;http://pic3.iqiyipic.com/image/20260525/7e/c7/pv_10277706445_em_601.jpg&quot;,&quot;w&quot;:1440,&quot;h&quot;:720}],&quot;link&quot;:{&quot;curl&quot;:&quot;https://web.biduwenxue.com/index?packagename=com.lujiao.quickapp&amp;channelCode=2011462&amp;callback=__CALLBACK__&amp;platform=iqiyi&amp;jumpPage=reader&amp;bookId=223611&amp;accountId=51200568831&amp;campaignId=65004846469&amp;adgroupId=66027990337&amp;contentId=67116468763&amp;callbackUrl=__CALLBACK_URL__&amp;oaid [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string android_admnative {
            get {
                return ResourceManager.GetString("android_admnative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///    &quot;id&quot;: &quot;d619ff0f098846cabe662f3428fd64ff&quot;,
        ///    &quot;bid&quot;: [
        ///        {
        ///            &quot;adzoneId&quot;: &quot;1623148675781639&quot;,
        ///            &quot;admnative&quot;: {
        ///                &quot;title&quot;: &quot;测试标题&quot;,
        ///                &quot;imgs&quot;: [
        ///                    {
        ///                        &quot;url&quot;: &quot;https://pic0.iqiyipic.com/image/20240821/d5/b5/pv_10044713499_em_601.jpg&quot;,
        ///                        &quot;w&quot;: 1200,
        ///                        &quot;h&quot;: 600
        ///                    }
        ///                ],
        ///                &quot;link&quot;: {
        ///                    &quot;curl&quot;: &quot;htt [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string android_imgs {
            get {
                return ResourceManager.GetString("android_imgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///    &quot;id&quot;: &quot;aef4e1b34d83476e88f3838817b79a91&quot;,
        ///    &quot;bid&quot;: [
        ///        {
        ///            &quot;adzoneId&quot;: &quot;1641566616277124&quot;,
        ///            &quot;crid&quot;: &quot;64000117925&quot;,
        ///            &quot;price&quot;: 9607500,
        ///            &quot;winNoticeUrl&quot;: [
        ///                &quot;http://track.ssp.iqiyi.com/ssp_track?xf=CMPG131MVn2TUuTCpLzrSQ!!&amp;qxt=http%3A%2F%2F10%2E16%2E189%2E224%2Fdsp%5Ftrack3%3Fblt%3D0%26poc%3D1%26acu%3D1%26bln%3D%25E7%25BB%2593%25E7%25AE%2597%25E6%25B5%258B%25E8%25AF%2595%25E7%2594%25A8%25E5%25B9%25BF%25E5%2591%258A%25E4%25B8%25BB%2 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string android_opening {
            get {
                return ResourceManager.GetString("android_opening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///    &quot;id&quot;: &quot;987119ef4a064ad4b61bb611cd33490c&quot;,
        ///    &quot;bid&quot;: [
        ///        {
        ///            &quot;adzoneId&quot;: &quot;1822397986058497&quot;,
        ///            &quot;crid&quot;: &quot;7100002867112697704&quot;,
        ///            &quot;price&quot;: 13,
        ///            &quot;winNoticeUrl&quot;: [
        ///                &quot;http://t7z.cupid.iqiyi.com/ssp_track?xn=1819483575856516&amp;xp=${AUCTION_PRICE}&amp;xf=T6f7vbQf7l1T6-Hbc4mbeA!!&amp;qxt=http%3A%2F%2Ft7z.cupid.iqiyi.com%2Fdsp_track3%3Ftcs%3DH4sIAAAAAAAAA31XW3eqOhf9LedBnj73SAghYY-RB1SsraJV1GpfHFwVBUHAS_n1ZwV3v9pzRo-jlYYkKzNz3Wa9MI-FpqT-rjxEAmva_7Aqf3X [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string android_opening2 {
            get {
                return ResourceManager.GetString("android_opening2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///    &quot;id&quot;: &quot;eade884840994792bfb36dd334c9603b&quot;,
        ///    &quot;bid&quot;: [
        ///        {
        ///            &quot;adzoneId&quot;: &quot;1623148712439937&quot;,
        ///            &quot;admnative&quot;: {
        ///                &quot;title&quot;: &quot;测试标题&quot;,
        ///                &quot;video&quot;: {
        ///                    &quot;url&quot;: &quot;http://data.video.iqiyi.com/videos/other/20240813/a0/33/015a30d0bdb186e83eb179a35bb6cb91.mp4?pv=0.2&quot;,
        ///                    &quot;duration&quot;: 45,
        ///                    &quot;startCover&quot;: &quot;http://static-s.iqiyi.com/common/20240813/ADS/b7/80/8d37a76b24.jpg&quot;,
        ///                    &quot;w&quot;: 1920 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string android_video {
            get {
                return ResourceManager.GetString("android_video", resourceCulture);
            }
        }
    }
}
